config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, :controllers => { 
  	:sessions => "sessions", 
  	registrations: "registrations"  
  }

  scope :path => "views" do 
  	resources :home
  end

  get 'about/terms' => 'about#terms'
  get 'about/privacy' => 'about#privacy'

  scope :path => "users/me" do 
    resources :questions
  end
  mount API => "/"

  mount Browserlog::Engine => '/logs'
end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :user
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	default_scope { order('created_at DESC') }

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

	GENDER = Hashie::Mash.new({
           	 MALE: "male",
           	 FEMALE: "female",
           }).freeze

  def set_default_role
    self.role ||= :user
  end

  has_many :cards, dependent: :destroy
  has_many :feedbacks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :partner_invitation_code

  has_one :partner, class_name: User.to_s, foreign_key: "partner_id"

  # TODO FIX 
  # validates :gender, inclusion: GENDER.values
  # validates :baby_name, presence: true, length: { :minimum => 1, :maximum => 128 }
  # validates :age, presence: true  
  # validates :height, presence: true
  # validates :weight, presence: true
  # validates :baby_due, presence: true

  validates :authentication_token, presence: true
  validates :notifications_days, presence: true, length: { is: 3 }, format: { with: /\A[0-9]+\z/,
    message: "only allows numbers" }

  # before_create :create_with_invitation_code, if: lambda { |user| user.partner_invitation_code }
  before_validation :ensure_authentication_token, on: :create
  before_validation :check_invitation_code, on: :create, if: lambda { |user| user.partner_invitation_code }

  after_create :set_opponent_partner #, if: "partner_id_changed?"
  after_create :generate_initial_cards

  def generate_invitation_code
    begin
      self.invitation_code = Digest::SHA1.hexdigest([Time.now, rand].join)[0,4].upcase
    end while User.find_by_invitation_code(self.invitation_code)
  end

  private

  def check_invitation_code  
    partner = User.find_by_invitation_code(self.partner_invitation_code)
    if partner
      self.partner_id = partner.id
      genders = GENDER.values
      genders.delete(partner.gender)
      self.gender = genders.first
    else
      self.errors.add(:partner_invitation_code, "It's invalid invitation code")
    end
  end

  def set_opponent_partner
    if partner_id
      partner = User.find_by_id(partner_id)
      partner.update_attribute(:partner_id, self.id)

      self.update_attributes({
        baby_due: partner.baby_due,
        baby_name: partner.baby_name
      })
    end
  end

  def generate_initial_cards  
    current_week = (((Time.zone.now - (self.baby_due - 10.months)) / 1.week).to_i) - 2

    card_week   = current_week
    cards_count = 0
    datas       = []

    while card_week >= 5 && card_week <= 40 && cards_count <= 15 do
      card_week -= 1
      3.times do |count|
        data = QuestionSheet.normal_data(self.gender, card_week, count)
        if (data)
          cards_count += 1
          datas.push({ 
            title: data[:title], 
            content: data[:content], 
            week: card_week, 
            resources_count: 0 
          })
        end
      end
    end

    ActiveRecord::Base.transaction do
      datas.reverse_each do |data|
        self.cards.create(data)
      end
    end
  end

  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.find_by_authentication_token(token)
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def terms
  end

  def privacy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout false 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout false 
	def index
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	layout false

	def new
		@user = User.find_by_authentication_token(params[:authentication_token])
		@question = QuestionSheet.question(params[:week].to_i, params[:count].to_i)
	end
	
	def create
		@user = User.find_by_authentication_token(params[:authentication_token])
		@answer = params[:answer].to_i != 0

		my_anwser_text = QuestionSheet.anwser_text(@answer, "female", params[:week].to_i, params[:count].to_i)
		@user.cards.create(title: my_anwser_text[:title], content: my_anwser_text[:content], week: params[:week].to_i, resources_count: 0)

		if @user.partner
			partner_anwser_text = QuestionSheet.anwser_text(@answer, "male", params[:week].to_i, params[:count].to_i)
			@user.partner.cards.create(title: partner_anwser_text[:title], content: partner_anwser_text[:content], week: params[:week].to_i, resources_count: 0)
		end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  skip_before_filter :verify_authenticity_token

  before_action :configure_permitted_parameters

  def create
    build_resource(sign_up_params)

    resource_saved = resource.save
    yield resource if block_given?
    if resource_saved
      if resource.active_for_authentication?
        sign_up(resource_name, resource)
        render( template: "users/auth.rabl" )
      else
        expire_data_after_sign_in!
        @user = resource
        render( template: "users/auth.rabl" )
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end
			render({ 
				json: { errors: resource.errors.full_messages }, 
				status: 422
			})
    end
  end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :gender, :baby_name, :age, :height, :weight, :baby_due, :partner_invitation_code, :notifications_days, :notificate_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  skip_before_filter :verify_authenticity_token
  
  def create
    self.resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
    sign_in(resource_name, resource)

    @user = self.resource
    render( template: "users/auth.rabl" )
  end

  def destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    render :json => {}
  end

  def failure
    warden.custom_failure!  
    render :json => { :errors => [flash[:alert]] }, status: 401
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.slim
// Main Page
doctype html
html ng-app="frenddy" ng-controller="ApplicationCtrl"
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Frenddy"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Frenddy'}"
    == stylesheet_link_tag "application", media: "all"
    == javascript_include_tag "application"
    == javascript_include_tag "//code.highcharts.com/highcharts.src.js"
    == csrf_meta_tags
  body
		div login-dialog=""
		  div ng-show="visible" ng-cloak="" class="fs-view login-dialog-view" ng-include="'#{asset_path("login_dialog.html")}'"
		div class="page-container" ng-switch="!!session.user"
		  div class="spinner" ng-switch-when="false"
		  div class="signed-view" ng-clock="" ng-switch-when="true"
		    nav class="navbar navbar-default" role="navigation" ng-controller="NavbarCtrl"
		      div class="container-fluid"
		        div class="navbar-header"
		          a class="navbar-brand" href="#" Frenddy
		          small = Daddys40::Application::START_TIME
		        div class="collapse navbar-collapse"
		          ul class="nav navbar-nav navbar-right"
		            li 
		              a 
		                | {{ session.user.name }}
		            li ng-if="session.user"
		              a href="" ng-click="signOut()" Sign Out
		    div ng-view=""
		  div class="non-signed-view" ng-clock="" ng-switch-when="false"

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.slim
// Main Page
doctype html
html ng-app="frenddy" ng-controller="ApplicationCtrl"
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Frenddy"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Frenddy'}"
    == stylesheet_link_tag "application", media: "all"
    == javascript_include_tag "application"
    == csrf_meta_tags
  body
    img src=asset_path("no_app_ios.png") width="100%" height="auto"

app/views/questions/create.html.slim
// Main Page
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Frenddy"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Frenddy'}"
    == stylesheet_link_tag("application", media: 'all')
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
  	div class="container"
      h3 접수되었습니다. 분석중...

app/views/questions/new.html.slim
// Main Page
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Frenddy"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Frenddy'}"
    == stylesheet_link_tag("application", media: 'all')
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
  	div class="container"
  		h4 
  			= "#{@user.name}님, "
  			= @question	
	    = form_tag questions_path, :method => :post do 
	    	= hidden_field_tag  :authentication_token, params[:authentication_token]
	    	= hidden_field_tag  :week, params[:week]
	    	= hidden_field_tag  :count, params[:count]
  			div class="radio"
  				label
  					input type="radio" name="answer" value="1" checked=""
  					b 예
  			div class="radio"
  				label
  					input type="radio" name="answer" value="1"
  					b 아니요	
  			button type="submit" class="btn btn-danger btn-sm btn-block" 
  				| 확인

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>